# Generated by Django 3.2 on 2022-05-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='selling_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklista', to='books.sellingplatform'),
        ),
    ]
