# Generated by Django 3.2 on 2022-05-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booklist_selling_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('star', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.booklist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
