# Generated by Django 3.2 on 2022-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
